# Generated by Django 3.2 on 2021-04-23 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='membership_end_date',
            field=models.DateField(null=True),
        ),
    ]
