# Generated by Django 3.2 on 2021-04-26 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='from_organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authz.organization'),
        ),
    ]
