# Generated by Django 3.2 on 2021-04-23 17:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authz', '0002_alter_organization_membership_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='membership_start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
