# Generated by Django 3.2 on 2021-04-23 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authz', '0003_alter_organization_membership_start_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name_plural': 'orgnization'},
        ),
    ]
