# Generated by Django 3.2 on 2021-04-24 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authz', '0004_alter_organization_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name_plural': 'Orgnizations'},
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_code',
            field=models.CharField(max_length=3, null=True, unique=True),
        ),
    ]
