# Generated by Django 3.2 on 2021-04-26 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authz', '0002_alter_user_from_organization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('description', models.TextField(max_length=255)),
                ('label', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relative_id', models.CharField(blank=True, max_length=8, null=True, unique=True)),
                ('name', models.CharField(max_length=127)),
                ('location', models.CharField(max_length=127)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('warranty', models.IntegerField(default=0)),
                ('last_repair', models.DateField(blank=True, null=True)),
                ('physical_address', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('digital_key', models.CharField(blank=True, max_length=48, null=True)),
                ('status', models.CharField(choices=[('available', 'AVAILABLE'), ('in use', 'IN_USE'), ('need maintenance', 'NEED_MAINTENANCE')], default='available', max_length=32)),
                ('note', models.TextField(blank=True, max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('asset_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_assets.category')),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_assets.manufacturer')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authz.organization')),
            ],
        ),
    ]
