# Generated by Django 3.2 on 2021-04-24 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.IntegerField(choices=[('available', 'AVAILABLE'), ('in use', 'IN_USE'), ('need maintenance', 'NEED_MAINTENANCE')], default='available'),
        ),
    ]
