# Generated by Django 3.2 on 2021-04-24 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authz', '0005_auto_20210425_0232'),
        ('my_assets', '0002_auto_20210425_0232'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authz.organization'),
        ),
        migrations.AddField(
            model_name='asset',
            name='relative_id',
            field=models.CharField(max_length=8, null=True, unique=True),
        ),
    ]
