# Generated by Django 3.2 on 2021-04-26 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_assets', '0002_alter_asset_date_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='date_created',
            new_name='registration_date',
        ),
    ]
