# Generated by Django 3.2 on 2021-04-26 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_assets', '0003_rename_date_created_asset_registration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='registration_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
