# Generated by Django 3.2 on 2021-04-27 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_assets', '0005_assestsfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCodeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('qrSvg', models.ImageField(blank=True, upload_to='QRCodes')),
            ],
        ),
    ]
