# Generated by Django 3.2 on 2021-04-27 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_assets', '0007_qrcodeimage_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcodeimage',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_assets.asset'),
        ),
    ]
