# Generated by Django 3.2 on 2021-04-29 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authz', '0002_alter_user_from_organization'),
        ('my_assets', '0008_alter_qrcodeimage_asset'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.AddField(
            model_name='category',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authz.organization'),
        ),
    ]
