# Generated by Django 3.2 on 2021-04-29 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authz', '0002_alter_user_from_organization'),
        ('my_assets', '0009_auto_20210429_1035'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_description', models.CharField(max_length=127)),
                ('requirement_date', models.DateField()),
                ('returning_date', models.DateField()),
                ('rq_msg', models.TextField(blank=True, max_length=200, null=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_assets.asset')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_assets.category')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authz.organization')),
                ('request_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assetrequest_request_to', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
