# Generated by Django 3.2 on 2021-04-29 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_side', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assetrequest',
            old_name='user',
            new_name='request_from',
        ),
    ]
