# Generated by Django 3.2 on 2021-05-02 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_side', '0002_rename_user_assetrequest_request_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('approved', 'APPROVED'), ('denied', 'DENIED')], default='pending', max_length=32),
        ),
    ]
