# Generated by Django 3.2 on 2021-05-03 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_side', '0003_assetrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetrequest',
            name='allocation_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='assetrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('approved', 'APPROVED'), ('denied', 'DENIED'), ('served', 'SERVED'), ('allocated', 'ALLOCATED')], default='pending', max_length=32),
        ),
    ]
